### ISSUE TITLE
Setup questions

### ISSUE THREAD

**Issue by fortminors** [VasilyMorzhakov/rembrain_robotframework#11]
Hello! I have several questions that came up after watching your demo. I would appreciate if you could answer them.

1. What is the simulator that you are using alongside VR kit?
2. How do you get such a precise depth measurement? I've seen during the demo there are flashes for each scan. Is it some special camera that does that? It looked to me that you are using Intel RealSense d435.

**Comment by VasilyMorzhakov** [comment]
Hello, @fortminors , this github project is about running multiple processes on the robot side + sending streams to our cluster, which is placed here: https://gitlab.com/rembrain/robotroom/-/tree/main/cluster_local   .  Raising the whole server backend might be not too trivial, plus huge gaps in deployment documentation are still there, I suppose. So let's keep the issue there and go through deployment.

**Comment by VasilyMorzhakov** [comment]
closed
